<?php

/**
 * @file
 * Main module file.
 */

/**
 * Implements hook_menu().
 */
function allocation_menu() {
  $items = array();

  $items['manage/allocation'] = array(
    'title' => 'Manage allocation',
    'page callback' => 'manage_allocation_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'includes/allocation.manage_allocation.inc',
  );

  $items['allocation_entry/%'] = array(
    'title' => 'Add Allocation',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('allocation_details_entry', 1),
    'access callback' => TRUE,
    'description' => 'Add Allocation',
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/allocation_details.inc',
  );

  return $items;
}

/**
 * fuction to fetch all head examiner.
 */
function exam_portal_all_head_examiner() {
  db_set_active('legecy');
  $query = db_select('head_examiners', 'he')
      ->fields('he', array('id', 'name'))
      ->execute();
  db_set_active('default'); // We need to call the main (drupal) db back      
  $result = $query->fetchAll();
  foreach ($result as $value) {
    $res[$value->id] = $value->name;
  }
  return $res;
}

/**
 * Total unallocted count based on paper id.
 */
function answersheet_unallocated_count($code) {
  db_set_active('legecy');
  $query = db_select('answer_sheets', 's');
  $query->fields('s', array('id'))
      ->condition('s.paper_code', $code)
      ->condition('s.STATUS', 'UNALLOCATED');
  $result = $query->execute()->rowCount();
  db_set_active('default');
  return $result;
}

/**
 * Get question details based on papercode.
 */
function questionpaper_details($code) {
  db_set_active('legecy');
  $query = db_select('question_papers', 'q');
  $query->fields('q')
      ->condition('q.paper_code', $code);
  $result = $query->execute()->fetchAll();
  db_set_active('default');
  return $result;
}
