<?php

/**
 * @file
 * The Allocation Details module.
 *
 * Provides allocation detail form fields.
 */

/**
 * Implements hook_menu.
 */
function portal_json_upload_menu() {
    $items = array();
    $items['import-portal'] = array(
      'title' => 'Upload JSON file',
      'description' => 'Import JSON',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('portal_json_import_form'),
      'access callback' => TRUE,        
      //'file' => 'portal_json_upload.inc',
    ); 
  
  return $items;
}


function portal_json_import_form($form, $form_state) {
  $form['notes'] = array(
    '#type' => 'markup',
    '#markup' => '<div class="import-notes">A file when uploading. <ul><li>Make sure the file is in a .json format.</li><li>Be sure to click the "Upload" button when you select a json.</li></ul></div>',
    '#upload_location' => 'public://tmp/',
  );
  $form['import'] = array(
    '#title' => t('Import'),
    '#type' => 'managed_file',
    '#description' => t('The uploaded json will be imported and temporarily saved.'),
    '#upload_location' => 'public://tmp/',
    '#upload_validators' => array(
      'file_validate_extensions' => array('json'),
    ),
  );
  $form['submit'] = array (
    '#type' => 'submit',
    '#value' => t('Import'),
  );
  return $form;    
}


/**
 * Submit handler for mcc_import_form()
 */
function portal_json_import_form_submit($form, $form_state) {
  // Check to make sure that the file was uploaded to the server properly
  $uri = db_query("SELECT uri FROM {file_managed} WHERE fid = :fid", array(
    ':fid' => $form_state['input']['import']['fid'],
  ))->fetchField();
  //print_r($uri);die();
  if(!empty($uri)) {
    if(file_exists(drupal_realpath($uri))) {
      $handle = fopen(drupal_realpath($uri), "r");
      $data = drupal_json_decode(file_get_contents($uri));

    foreach ($data as $values) {
        $operations[] = array(
           'portal_json_import_batch_processing',  // The function to run on each row
            array($values),  // The row in the csv
        );    
    }       
            
      // Once everything is gathered and ready to be processed... well... process it!
      $batch = array(
        'title' => t('Importing JSON...'),
        'operations' => $operations,  // Runs all of the queued processes from the while loop above.
        'finished' => 'portal_json_import_finished', // Function to run when the import is successful
        'error_message' => t('The installation has encountered an error.'),
        'progress_message' => t('Imported @current of @total.'),
      );
      batch_set($batch);
      fclose($handle);
      //db_set_active('default');
    }
  }
  else {
    drupal_set_message(t('There was an error uploading your file. Please contact a System administator.'), 'error');
  }
}


/**
 * This function runs the batch processing and creates nodes with then given information
 * @see
 * mcc_import_form_submit()
 */
function portal_json_import_batch_processing($values) {
    db_set_active('legecy');
    $question_insert = db_insert('answer_sheets') // Table name no longer needs {}
    ->fields(array(
        "id" => $values['id'],
        "paper_code" => $values['paper_code'],
        "sheet_name" => $values['sheet_name'],
        "subject_code" => $values['subject_code'],
        "region_code" => $values['region_code'],
        "exam_code" => $values['exam_code'],
        //"center_code" => "",
        "paper_set" => $values['paper_set'],
        "language" => $values['language'],
        "status" => $values['status'],
        "evaluation_marks" => $values['evaluation_marks'],
        //"marks_by_examiner" => "20",
        //"marks_by_headexaminer" => "20",
        "re_evaluation_marks" => $values['re_evaluation_marks'],
        "alloted_to" => $values['alloted_to'],
        "head_examiner" => $values['head_examiner'],
        "examiner" => $values['examiner'],
        //"downloadstatus" => "1",
        //"allocation_log_id" => "0",
        //"examiner_allocation_log_id" => "0"
    ))
    ->execute();    
    db_set_active('default');
}


/**
 * This function runs when the batch processing is complete
 *
 * @see
 * mcc_import_form_submit()
 */
function portal_json_import_finished() {
  drupal_set_message(t('Import Completed Successfully'));
}


